include:
    - apps.alacritty
    - apps.vim
    - apps.vscode
    - desktop.gnome
    - desktop.gtk
    - desktop.i3
    - development.docker
    - development.git
    - development.go
    - shells.zsh
    - system.bluetooth
    - system.yubikey-gpg
