export KUBECTL_CONTEXT_SWITCHER_GT8=code.devtech.gt8.online=gke_gt8-mindetic_europe-west1-b_production
export KUBECTL_CONTEXT_SWITCHER_GLOFOX=bitbucket.org/glofox=gke_glofox-platform_europe-west1-b_production
