export PATH=$PATH:~/.composer/vendor/bin

source /opt/base16-shell/scripts/base16-materia.sh

source ~/.zshrc.common

# Antigen
# source /opt/zsh-antigen/antigen.zsh
# source ~/.zshrc.antigen

# Zplug
source ~/.zplug/init.zsh
source ~/.zshrc.zplug

if [[ -f ~/.zshrc.local ]];
then
    source ~/.zshrc.local
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
