export PATH=$PATH:~/.composer/vendor/bin

source /opt/base16-shell/scripts/base16-materia.sh

source ~/.zshrc.common

# Antigen
# source /opt/zsh-antigen/antigen.zsh
# source ~/.zshrc.antigen

# Zplug
source ~/.zplug/init.zsh
source ~/.zshrc.zplug

if [[ -f ~/.zshrc.local ]];
then
    source ~/.zshrc.local
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Start or re-use a gpg-agent.
gpgconf --launch gpg-agent

# Ensure that GPG Agent is used as the SSH agent
export SSH_AUTH_SOCK=~/.gnupg/S.gpg-agent.ssh

