export PATH=$PATH:~/.composer/vendor/bin

source ~/.zshrc.common
source ~/.zshrc.keybindings

source ~/.zplug/init.zsh
source ~/.zshrc.zplug

# fzf Fuzzy Finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source ~/.zshrc.gpg-agent

# Load local overrides last
if [[ -f ~/.zshrc.local ]];
then
    source ~/.zshrc.local
fi
